import { Router } from 'express';
import { authRouter } from './auth.routes';
import { usersRouter } from './users.routes';
import { curriculumRouter } from './curriculum.routes';
import { lessonsRouter } from './lessons.routes';
import { quizzesRouter } from './quizzes.routes';
import { problemsRouter } from './problems.routes';
import { assignmentsRouter } from './assignments.routes';
import { submissionsRouter } from './submissions.routes';
import { aiRouter } from './ai.routes';
import { progressRouter } from './progress.routes';
import { gamificationRouter } from './gamification.routes';
import { projectsRouter } from './projects.routes';
import { adminRouter } from './admin.routes';
import { analyticsRouter } from './analytics.routes';
import { intelligenceRouter } from './intelligence.routes';
import { mentorRouter } from './mentor.routes';
import { assessmentRouter } from './assessment.routes';
import { contestRouter } from './contest.routes';
import { leaderboardRouter } from './leaderboard.routes';
import { ratingRouter } from './rating.routes';
import { portfolioRouter } from './portfolio.routes';
import { groupRouter } from './group.routes';
import { forumRouter } from './forum.routes';
import { careerRouter } from './career.routes';
import { interviewRouter } from './interview.routes';
import { resumeRouter } from './resume.routes';
import { talentRouter } from './talent.routes';
import { activityRouter } from './activity.routes';
import { judgeRouter } from './judge.routes';
import { companiesRouter } from './companies.routes';
import { jobsRouter } from './jobs.routes';
import { applicationsRouter } from './applications.routes';
import { careerAdvisorRouter } from './careerAdvisor.routes';
import { referralRouter } from './referral.routes';
import { hiringChallengesRouter } from './hiringChallenges.routes';
import { interviewsPipelineRouter } from './interviewsPipeline.routes';
import { organizationsRouter } from './organizations.routes';
import { universitiesRouter } from './universities.routes';
import { facultyMentorsRouter } from './facultyMentors.routes';
import { lmsRouter } from './lms.routes';
import { certificationsRouter } from './certifications.routes';
import { workforceIntelligenceRouter } from './workforceIntelligence.routes';
import { analyticsExecutiveRouter } from './analyticsExecutive.routes';
import { adminCopilotRouter } from './adminCopilot.routes';

export const v1Router = Router();

v1Router.use('/auth', authRouter);
v1Router.use('/users', usersRouter);
v1Router.use('/curriculum', curriculumRouter);
v1Router.use('/lessons', lessonsRouter);
v1Router.use('/quizzes', quizzesRouter);
v1Router.use('/problems', problemsRouter);
v1Router.use('/assignments', assignmentsRouter);
v1Router.use('/submissions', submissionsRouter);
v1Router.use('/judge', judgeRouter);
v1Router.use('/ai', aiRouter);
v1Router.use('/progress', progressRouter);
v1Router.use('/gamification', gamificationRouter);
v1Router.use('/projects', projectsRouter);
v1Router.use('/admin', adminRouter);
v1Router.use('/analytics', analyticsRouter);
v1Router.use('/intelligence', intelligenceRouter);
v1Router.use('/mentor', mentorRouter);
v1Router.use('/assessments', assessmentRouter);
v1Router.use('/contests', contestRouter);
v1Router.use('/leaderboards', leaderboardRouter);
v1Router.use('/ratings', ratingRouter);
v1Router.use('/portfolio', portfolioRouter);
v1Router.use('/groups', groupRouter);
v1Router.use('/forum', forumRouter);
v1Router.use('/career', careerRouter);
v1Router.use('/interviews', interviewRouter);
v1Router.use('/resumes', resumeRouter);
v1Router.use('/talent', talentRouter);
v1Router.use('/feed', activityRouter);
v1Router.use('/companies', companiesRouter);
v1Router.use('/jobs', jobsRouter);
v1Router.use('/applications', applicationsRouter);
v1Router.use('/advisor', careerAdvisorRouter);
v1Router.use('/referrals', referralRouter);
v1Router.use('/hiring-challenges', hiringChallengesRouter);
v1Router.use('/pipeline', interviewsPipelineRouter);
v1Router.use('/organizations', organizationsRouter);
v1Router.use('/universities', universitiesRouter);
v1Router.use('/faculty-mentors', facultyMentorsRouter);
v1Router.use('/lms', lmsRouter);
v1Router.use('/certifications', certificationsRouter);
v1Router.use('/workforce-intelligence', workforceIntelligenceRouter);
v1Router.use('/analytics-executive', analyticsExecutiveRouter);
v1Router.use('/admin-copilot', adminCopilotRouter);

