export * from './academicProgramsService';
export * from './scientificDiscoveryService';
export * from './digitalLaboratoryService';
export * from './academicKnowledgeGraphService';
export * from './publicationEngineService';
export * from './peerReviewNetworkService';
export * from './researchFundingService';
export * from './globalCollaborationService';
export * from './researchMetricsService';
